add kubernetes cronjob and logic
ONSdigital/rm-sample-service pull request #126
Opened 2020-07-03 17:40 UTC by jterryons

Add kubernetes cron job to handle the Sample service cron

2020-07-03 18:17 UTC, jterryons commented
/deploy terryj

2020-07-03 18:25 UTC, jterryons commented
/deploy terryj

2020-07-03 18:30 UTC, jterryons commented
/deploy terryj

2020-07-03 18:53 UTC, jterryons commented
/deploy terryj

2020-07-03 20:04 UTC, jterryons commented
/deploy terryj

2020-07-03 20:23 UTC, jterryons commented
/deploy terryj

2020-07-06 12:09 UTC, jterryons commented
/deploy terryj

2020-07-06 16:36 UTC, jterryons commented
/deploy terryj

2020-07-06 16:50 UTC, jterryons commented
/deploy terryj

2020-07-06 17:14 UTC, jterryons commented
/deploy terryj

2020-11-20 10:26 UTC, jterryons commented
/deploy terryj

2020-11-20 11:11 UTC, jterryons commented
/deploy terryj

2020-11-20 11:36 UTC, jterryons commented
/deploy terryj

2020-11-20 12:01 UTC, jterryons commented
/deploy terryj

2020-11-23 09:11 UTC, jterryons commented
/deploy terryj

2020-11-23 09:35 UTC, insacuri commented on .github/workflows/main.yml
> -          mvn fmt:check
You sure we should be removing this?

2020-11-23 09:36 UTC, mfcrocker commented on .github/workflows/main.yml
> -          mvn fmt:check
I would be very happy if we did

2020-11-23 11:08 UTC, insacuri commented
/deploy manna

2020-11-23 12:00 UTC, insacuri requested changes
One small comment, other then that it looks good.  Just testing it locally now

2020-11-23 12:00 UTC, insacuri commented on _infra/helm/sample/templates/cronjob.yaml
> +                curl -X POST "http://{{ .Chart.Name }}:{{ .Values.dns.wellKnownPort }}/samples/export" -H "accept: application/json"
One very small nit pick.  Can you add the -s and -S flags to this like in https://github.com/ONSdigital/rm-collection-exercise-service/blob/master/_infra/helm/collection-exercise/templates/distribute-sample-unit-cronjob.yaml#L37

The reason for this is that you get a bunch of 
```
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
```
and 
```
% Total % Received % Xferd Average Speed Time Time Time Current
```
 'error' logs when you don't suppress the output

2020-11-23 12:26 UTC, jterryons commented
/deploy terryj

2020-11-23 13:01 UTC, insacuri commented
/deploy manna

2020-11-23 13:19 UTC, insacuri commented
/deploy manna

2020-11-23 13:25 UTC, insacuri approved these changes

2020-11-23 14:15 UTC, merged