removing sample file upload code
ONSdigital/rm-sample-service pull request #137
Opened 2020-10-23 09:54 UTC by anwilkie

# Motivation and Context
Now that sample file uploader has been created, this service no longer needs to handle sample files. The `/samples/type/fileupload` endpoint and all related code needed to be deleted.

# What has changed
* Removed the `/samples/type/fileupload` endpoint from `SampleEndpoint.java`
* Removed documentation for the above endpoint from openapi.yaml
* Removed all unit tests relating to the above endpoint from SampleEndpointUnitTest.java
* Deleted the entire SampleEndpointIT.java file, as there were only two tests in the file, both of which involved the endpoint.
* Deleted a script file for file uploads

# Links
[Trello card](https://trello.com/c/QJFRTtZB)

2020-10-23 14:47 UTC, jterryons requested changes

2020-10-23 14:47 UTC, jterryons commented on src/main/java/uk/gov/ons/ctp/response/sample/endpoint/SampleEndpoint.java
> -      SampleSummary result = ingest(file, type);
could you also remove this `ingest` fucntion? That function calls an ingest function in the SampleService class. that will need to be remove too and anything else within those functions that relate to file processing

2020-10-28 10:13 UTC, bkhan2 approved these changes

2020-10-28 11:19 UTC, warrenbailey approved these changes

2020-10-29 09:22 UTC, merged